name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        install: true
        driver-opts: |
          image=moby/buildkit:master

    - name: Cache pip
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: pip-cache-${{ runner.os }}-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          pip-cache-${{ runner.os }}-

    - name: Build, tag and push Docker image to ECR (with cache)
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: 537124934274.dkr.ecr.us-east-2.amazonaws.com/route-map-match:latest
        cache-from: type=registry,ref=537124934274.dkr.ecr.us-east-2.amazonaws.com/route-map-match:cache
        cache-to: type=registry,ref=537124934274.dkr.ecr.us-east-2.amazonaws.com/route-map-match:cache,mode=max